package ArenaBot.Resources;

import java.util.HashMap;

public class Flags
{

	public static HashMap<String, String> getFlags()
	{

		HashMap<String, String> flags = new HashMap <>();

		//A Flags
		flags.put(":flag_ac:", "Ascension Island");
		flags.put(":flag_ad:", "Andorra");
		flags.put(":flag_ae:", "United Arab Emirates");
		flags.put(":flag_af:", "Afghanistan");
		flags.put(":flag_ag:", "Antigua and Barbuda");
//		flags.put(":flag_ai:", "Anguilla");
//		flags.put(":flag_al:", "Albania");
//		flags.put(":flag_am:", "Armenia");
//		flags.put(":flag_ao:", "Angola");
//		flags.put(":flag_aq:", "Antarctica");
//		flags.put(":flag_ar:", "Argentina");
//		flags.put(":flag_as:", "American Samoa");
//		flags.put(":flag_at:", "Austria");
//		flags.put(":flag_au:", "Australia");
//		flags.put(":flag_aw:", "Aruba");
//		flags.put(":flag_ax:", "Åland");
//		flags.put(":flag_az:", "Azerbaijan");

		//B Flags
//		flags.put(":flag_ba:", "Bosnia and Herzegovina");
//		flags.put(":flag_bb:", "Barbados");
//		flags.put(":flag_bd:", "Bangladesh");
//		flags.put(":flag_be:", "Belgium");
//		flags.put(":flag_bf:", "Burkina Faso");
//		flags.put(":flag_bg:", "Bulgaria");
//		flags.put(":flag_bh:", "Bahrain");
//		flags.put(":flag_bi:", "Burundi");
//		flags.put(":flag_bj:", "Benin");
//		flags.put(":flag_bl:", "Saint Barthélemy");
		//flags.put("", "");

		flags.put(":flag_ic:", "Canary Islands");
		flags.put(":flag_id:", "Indonesia");
		flags.put(":flag_ie:", "Ireland");
		flags.put(":flag_il:", "Israel");
		flags.put(":flag_im:", "Isle of Man");
		flags.put(":flag_in:", "India");
		flags.put(":flag_io:", "British Indian Ocean Territory");
		flags.put(":flag_iq:", "Iraq");
		flags.put(":flag_ir:", "Iran");
		flags.put(":flag_is:", "Iceland");
		flags.put(":flag_it:", "Italy");
		flags.put(":flag_je:", "Jersey");
		flags.put(":flag_jm:", "Jamaica");
		flags.put(":flag_jo:", "Jordan");
		flags.put(":flag_jp:", "Japan");
		flags.put(":flag_ke:", "Kenya");
		flags.put(":flag_kg:", "Kyrgyzstan");
		flags.put(":flag_kh:", "Cambodia");
		flags.put(":flag_ki:", "Kiribati");
		flags.put(":flag_km:", "Comoros");
		flags.put(":flag_kn:", "Saint Kitts and Nevis");
		flags.put(":flag_kp:", "North Korea");
		flags.put(":flag_kr:", "South Korea");
		flags.put(":flag_kw:", "Kuwait");
		flags.put(":flag_ky:", "Cayman Islands");
		flags.put(":flag_kz:", "Kazakhstan");
		flags.put(":flag_la:", "Laos");
		flags.put(":flag_lb:", "Lebanon");
		flags.put(":flag_lc:", "Saint Lucia");
		flags.put(":flag_li:", "Liechtenstein");
		flags.put(":flag_lk:", "Sri Lanka");
		flags.put(":flag_lr:", "Liberia");
		flags.put(":flag_ls:", "Lesotho");
		flags.put(":flag_lt:", "Lithuania");
		flags.put(":flag_lu:", "Luxembourg");
		flags.put(":flag_lv:", "Latvia");
		flags.put(":flag_ly:", "Libya");
		flags.put(":flag_ma:", "Morocco");
		flags.put(":flag_mc:", "Monaco");
		flags.put(":flag_md:", "Moldova");
		flags.put(":flag_me:", "Montenegro");
		flags.put(":flag_mf:", "Collectivity of Saint Martin");
		flags.put(":flag_mg:", "Madagascar");
		flags.put(":flag_mh:", "Marshall Islands");
		flags.put(":flag_mk:", "North Macedonia");
		flags.put(":flag_ml:", "Mali");
		flags.put(":flag_mm:", "Myanmar");
		flags.put(":flag_mn:", "Mongolia");
		flags.put(":flag_mo:", "Macau");
		flags.put(":flag_mp:", "North Mariana Islands");
		flags.put(":flag_mq:", "Martinique");
		flags.put(":flag_mr:", "Mauritania");
		flags.put(":flag_ms:", "Monsterrat");
		flags.put(":flag_mt:", "Malta");
		flags.put(":flag_mu:", "Mauritius");
		flags.put(":flag_mv:", "Maldives");
		flags.put(":flag_mw:", "Malawi");
		flags.put(":flag_mx:", "Mexico");
		flags.put(":flag_my:", "Malaysia");
		flags.put(":flag_mz:", "Mozambique");
		flags.put(":flag_na:", "Namibia");
		flags.put(":flag_nc:", "New Caledonia");
		flags.put(":flag_ne:", "Niger");
		flags.put(":flag_nf:", "Norfolk Island");
		flags.put(":flag_ng:", "Nigeria");
		flags.put(":flag_ni:", "Nicaragua");
		flags.put(":flag_nl:", "The Netherlands");
		flags.put(":flag_no:", "Norway");
		flags.put(":flag_np:", "Nepal");
		flags.put(":flag_nr:", "Nauru");
		flags.put(":flag_nu:", "Niue");
		flags.put(":flag_nz:", "New Zealand");
		flags.put(":flag_om:", "Oman");
		flags.put(":flag_pa:", "Panama");
		flags.put(":flag_pe:", "Peru");
		flags.put(":flag_pf:", "French Polynesia");
		flags.put(":flag_pg:", "Papua New Guinea");
		flags.put(":flag_ph:", "Philippines");
		flags.put(":flag_pk:", "Pakistan");
		flags.put(":flag_pl:", "Poland");
		flags.put(":flag_pm:", "Saint-Pierre and Miquelon");
		flags.put(":flag_pn:", "Pitcairn Islands");
		flags.put(":flag_pr:", "Puerto Rico");
		flags.put(":flag_ps:", "Palestine");
		flags.put(":flag_pt:", "Portugal");
		flags.put(":flag_pw:", "Palau");
		flags.put(":flag_py:", "Paraguay");
		flags.put(":flag_qa:", "Qatar");
		flags.put(":flag_re:", "Reunion");
		flags.put(":flag_ro:", "Romania");
		flags.put(":flag_rs:", "Serbia");
		flags.put(":flag_ru:", "Russia");
		flags.put(":flag_rw:", "Rwanda");
		flags.put(":flag_sa:", "Saudi Arabia");
		flags.put(":flag_sb:", "Solomon Islands");
		flags.put(":flag_sc:", "Seychelles");
		flags.put(":flag_sd:", "Sudan");
		flags.put(":flag_se:", "Sweden");
		flags.put(":flag_sg:", "Singapore");
		flags.put(":flag_sh:", "Saint Helena");
		flags.put(":flag_si:", "Slovenia");
		flags.put(":flag_sj:", "Svalbard and Jan Mayen Islands");
		flags.put(":flag_sl:", "Sierra Leone");
		flags.put(":flag_sm:", "San Marino");
		flags.put(":flag_sn:", "Senegal");
		flags.put(":flag_so:", "Somalia");
		flags.put(":flag_sr:", "Suriname");
		flags.put(":flag_ss:", "South Sudan");
		flags.put(":flag_st:", "Sao Tome and Principe");
		flags.put(":flag_sv:", "El Salvador");
		flags.put(":flag_sx:", "Sint Maarten");
		flags.put(":flag_sy:", "Syria");
		flags.put(":flag_sz:", "eSwatini");
		flags.put(":flag_ta:", "Tristan Da Cunha");
		flags.put(":flag_tc:", "Turks and Caicos Islands");
		flags.put(":flag_td:", "Chad");
		flags.put(":flag_tf:", "French Southern lands Antarctic Lands");
		flags.put(":flag_tg:", "Togo");
		flags.put(":flag_th:", "Thailand");
		flags.put(":flag_tj:", "Tajikistan");
		flags.put(":flag_tk:", "Tokelau");
		flags.put(":flag_tl:", "East Timor");
		flags.put(":flag_tm:", "Turkmenistan");
		flags.put(":flag_tn:", "Tunisia");
		flags.put(":flag_to:", "Tonga");
		flags.put(":flag_tr:", "Turkey");
		flags.put(":flag_tt:", "Trinidad and Tobago");
		flags.put(":flag_tv:", "Tuvalu");
		flags.put(":flag_tw:", "Taiwan");
		flags.put(":flag_tz:", "Tanzania");
		flags.put(":flag_ua:", "Ukraine");
		flags.put(":flag_ug:", "Uganda");
		flags.put(":flag_um:", "United States Minor Outlying Islands");
		flags.put(":flag_us:", "United States of America");
		flags.put(":flag_uy:", "Uruguay");
		flags.put(":flag_uz:", "Uzbekistan");
		flags.put(":flag_va:", "Vatican City");
		flags.put(":flag_vc:", "Saint Vincent and the Grenadines");
		flags.put(":flag_ve:", "Venezuela");
		flags.put(":flag_vg:", "British Virgin Islands");
		flags.put(":flag_vi:", "United States Virgin Islands");
		flags.put(":flag_vn:", "Vietnam");
		flags.put(":flag_vu:", "Vanuatu");
		flags.put(":flag_wf:", "Wallis and Futuna");
		flags.put(":flag_ws:", "Samoa");
		flags.put(":flag_ye:", "Yemen");
		flags.put(":flag_yt:", "Mayotte");
		flags.put(":flag_za:", "South Africa");
		flags.put(":flag_zm:", "Zambia");
		flags.put(":flag_zw:", "Zimbabwe");

		return flags;

	}
}
